version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/log:/var/log/nginx
    ports:
      - "7030:80"
      - "3030:443"
    restart: always
    links:
      - php
    depends_on:
      - php
      - mysqldb
  php:
    build: docker/php
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/local-conf.d/:/usr/local/etc/php/local-conf.d/
    restart: always
    depends_on:
      - mysqldb
  cerbot:
    build: docker/cerbot
    command: tail -F anything
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./docker/nginx/:/etc/nginx/
    ports:
      - "7031:80"
    depends_on:
      - web
  db:
    image: postgres:17.2
    restart: always
    env_file:
      - ".env"
    ports:
      - "6030:5432"
    environment:
      - POSTGRES_DB=${PGSQL_DATABASE}
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
    volumes:
      - ./data/pgdb/:/var/lib/postgresql/data/
    logging:
      options:
        max-size: "10m"
        max-file: "3"