services:
  ivsevolod-backend:
    restart: unless-stopped
    image: ivsevolod-backend
    networks:
      - ivsevolod-net
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/php/Dockerfile
    healthcheck:
      disable: true
    volumes:
      - ./ivsevolod/app:/app

  ivsevolod-nginx:
    restart: unless-stopped
    image: ivsevolod-nginx
    networks:
      - ivsevolod-net
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/nginx/Dockerfile
    depends_on:
      - ivsevolod-backend
    volumes:
      - ./ivsevolod/app/public:/app/public
      - ./ivsevolod/data/nginx/log:/var/log/nginx
      - ./ivsevolod/data/nginx/data/conf.d:/etc/nginx/conf.d

networks:
  ivsevolod-net:
    driver: bridge