services:
  ivsevolod-backend:
    restart: unless-stopped
    image: ivsevolod-backend
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/php/Dockerfile
    healthcheck:
      disable: true
    volumes:
      - ./ivsevolod/app:/app

  ivsevolod-nginx:
    restart: unless-stopped
    image: ivsevolod-nginx
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/nginx/Dockerfile
    depends_on:
      - ivsevolod-backend
    volumes:
      - ./ivsevolod/app/public:/app/public
      - ./ivsevolod/data/nginx/log:/var/log/nginx
      - ./ivsevolod/data/nginx/data/conf.d:/etc/nginx/conf.d

  gateway:
    restart: unless-stopped
    image: gateway-nginx
    networks:
      - ivsevolod-net
    build:
      dockerfile: gateway/nginx/${APK_ENV}/Dockerfile
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./gateway/data/nginx/data/conf.d:/etc/nginx/conf.d
      - ./gateway/data/nginx/log:/var/log/nginx
    depends_on:
      - ivsevolod-nginx
    ports:
      - 7030:80
      - 3030:443

networks:
  ivsevolod-net:
    driver: bridge