services:
  main-backend:
    restart: unless-stopped
    image: ivsevolod-backend
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/php/Dockerfile
    healthcheck:
      disable: true
    volumes:
      - ./ivsevolod/app:/app

  main-nginx:
    restart: unless-stopped
    image: ivsevolod-nginx
    build:
      dockerfile: ivsevolod/docker/${APK_ENV}/nginx/Dockerfile
    depends_on:
      - main-backend
    volumes:
      - ./ivsevolod/app/public:/app/public
      - ./ivsevolod/data/nginx/log:/var/log/nginx
      - ./ivsevolod/data/nginx/data/conf.d:/etc/nginx/conf.d

  gateway:
    restart: unless-stopped
    image: gateway-nginx
    build:
      dockerfile: gateway/nginx/${APK_ENV}/Dockerfile
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./gateway/data/nginx/data/conf.d:/etc/nginx/conf.d
      - ./gateway/data/nginx/log:/var/log/nginx
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - main-nginx
    ports:
      - 7030:80
      - 3030:443

  certbot:
#    https://phoenixnap.com/kb/letsencrypt-docker
    restart: "no"
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw